version: '3'

services:

  apt-cacher-ng:
    build:
      context: apt-cacher-ng
      args:
        UPSTREAM_APT_PROXY: ${UPSTREAM_APT_PROXY}
    volumes:
      - ./cache:/var/cache/apt-cacher-ng:rw

  kali-live-build:
    build:
      context: kali-live-build
      args:
        UPSTREAM_APT_PROXY: ${UPSTREAM_APT_PROXY}
    tty: true
    stdin_open: true
    depends_on:
      - apt-cacher-ng
    volumes:
      - ./kali-live-build/images:/live-build-config/images
      - ./kali-live-build/live-chroot:/live-build-config/chroot
      - /proc:/proc
