version: '3'

services:

  apt-cacher-ng:
    build:
      context: apt-cacher-ng
      args:
        UPSTREAM_PROXY: ${UPSTREAM_PROXY}
    volumes:
      - ./cache:/var/cache/apt-cacher-ng:rw

  kali-live-build:
    build:
      context: kali-live-build
      args:
        UPSTREAM_PROXY: ${UPSTREAM_PROXY}
    environment:
      - OVERRIDE_PROFILE
    depends_on:
      - apt-cacher-ng
    # For --installer, it work without the privileged flag, but build live build seems to need this
    privileged: true
    volumes:
      - ./kali-live-build/images:/live-build-config/images
      - ./kali-live-build/overrides:/overrides
      - /proc:/proc
